//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinTin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32768.
        /// </summary>
        internal static string BUFFER_SIZE {
            get {
                return ResourceManager.GetString("BUFFER_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinTin.Config.Class-Schema.json.
        /// </summary>
        internal static string CLASS_SCHEMA {
            get {
                return ResourceManager.GetString("CLASS_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string COMMAND_SEPARATOR {
            get {
                return ResourceManager.GetString("COMMAND_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string DEFAULT_CLOSE {
            get {
                return ResourceManager.GetString("DEFAULT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string DEFAULT_OPEN {
            get {
                return ResourceManager.GetString("DEFAULT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string ESCAPE {
            get {
                return ResourceManager.GetString("ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinTin.Help.Help.xsd.
        /// </summary>
        internal static string HELP_SCHEMA {
            get {
                return ResourceManager.GetString("HELP_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.txt.
        /// </summary>
        internal static string HISTORY_FILE {
            get {
                return ResourceManager.GetString("HISTORY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string LEGEND_SIZE {
            get {
                return ResourceManager.GetString("LEGEND_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string LIST_MESSAGE {
            get {
                return ResourceManager.GetString("LIST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string LIST_SIZE {
            get {
                return ResourceManager.GetString("LIST_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        internal static string MAX_STR_HASH {
            get {
                return ResourceManager.GetString("MAX_STR_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string NUMBER_SIZE {
            get {
                return ResourceManager.GetString("NUMBER_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PULSE_PER_SECOND {
            get {
                return ResourceManager.GetString("PULSE_PER_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string SCREEN_HEIGHT {
            get {
                return ResourceManager.GetString("SCREEN_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        internal static string SCREEN_WIDTH {
            get {
                return ResourceManager.GetString("SCREEN_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string STR_HASH_FLAG_NOGREP {
            get {
                return ResourceManager.GetString("STR_HASH_FLAG_NOGREP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65536.
        /// </summary>
        internal static string STRING_SIZE {
            get {
                return ResourceManager.GetString("STRING_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string TINTIN_CHAR {
            get {
                return ResourceManager.GetString("TINTIN_CHAR", resourceCulture);
            }
        }
    }
}
