//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public char PromptChar {
            get {
                return ((char)(this["PromptChar"]));
            }
            set {
                this["PromptChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public char COMMAND_SEPARATOR {
            get {
                return ((char)(this["COMMAND_SEPARATOR"]));
            }
            set {
                this["COMMAND_SEPARATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("}")]
        public char DEFAULT_CLOSE {
            get {
                return ((char)(this["DEFAULT_CLOSE"]));
            }
            set {
                this["DEFAULT_CLOSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{")]
        public char DEFAULT_OPEN {
            get {
                return ((char)(this["DEFAULT_OPEN"]));
            }
            set {
                this["DEFAULT_OPEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int ESCAPE {
            get {
                return ((int)(this["ESCAPE"]));
            }
            set {
                this["ESCAPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".tt_history")]
        public string HISTORY_FILE {
            get {
                return ((string)(this["HISTORY_FILE"]));
            }
            set {
                this["HISTORY_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LIST_MESSAGE {
            get {
                return ((int)(this["LIST_MESSAGE"]));
            }
            set {
                this["LIST_MESSAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MAX_STR_HASH {
            get {
                return ((int)(this["MAX_STR_HASH"]));
            }
            set {
                this["MAX_STR_HASH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int PULSE_PER_SECOND {
            get {
                return ((int)(this["PULSE_PER_SECOND"]));
            }
            set {
                this["PULSE_PER_SECOND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int SCREEN_HEIGHT {
            get {
                return ((int)(this["SCREEN_HEIGHT"]));
            }
            set {
                this["SCREEN_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SCREEN_WIDTH {
            get {
                return ((int)(this["SCREEN_WIDTH"]));
            }
            set {
                this["SCREEN_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int STR_HASH_FLAG_NOGREP {
            get {
                return ((int)(this["STR_HASH_FLAG_NOGREP"]));
            }
            set {
                this["STR_HASH_FLAG_NOGREP"] = value;
            }
        }
    }
}
